### ISSUE TITLE
Data channel descriptions

### ISSUE THREAD

**Issue by xdumaine** [otalk/jxt-xmpp#9] opened 2015-12-09 01:27 UTC
@legastero I have this added to `jingle-stanza` which helps define data descriptions in jingle contents. Would this fit into this project?

``` javascript
    var DCNS = 'urn:xmpp:jingle:transports:webrtc-datachannel:0';
    var DataChannel = stanza.define({
        name: '_datachannel',
        namespace: DCNS,
        element: 'description',
        tags: ['jingle-description'],
        fields: {
            descType: {value: 'datachannel'}
        }
    });

   ...

    stanza.withDefinition('content', 'urn:xmpp:jingle:1', function (Content) {
        stanza.extend(Content, RTP);
        stanza.extend(Content, DataChannel);
    });
```

**Comment by legastero** [comment] 2015-12-09 03:19
:grimacing:

This will likely conflict with Talky since we're already using `http://talky.io/ns/datachannel` for this same sort of registration. We'd need to go through an app review and release to get the iOS app to use the new namespace before this could be merged.

I'm +1 on merging a PR for this once that is done.

**Comment by xdumaine** [comment] 2015-12-09 03:58
Could do a minor version bump and limit talky's version until the iOS
version is through, right?

**Comment by fippo** [comment] 2015-12-09 16:35
how do you plan to use the urn:xmpp:jingle:transports:webrtc-datachannel:0 namespace? In xep 0343 it is only used for explicit signaling of channels

**Comment by xdumaine** [comment] 2015-12-09 18:04
That's what I have for data channel descriptions on session init coming from the focus controller.

``` xml
<iq xmlns="jabber:client" to="56686cf20000466624d0aa1e@test.com" from="someroom-56686cf20000466624d2dc23@test.com" type="set" id="565dd8db00000b19a4eb6234">
   <jingle xmlns="urn:xmpp:jingle:1" sid="3d81d028b2d19cf" action="session-accept">
      <group xmlns="urn:xmpp:jingle:apps:grouping:0">
         <content name="video" />
         <content name="audio" />
         <content name="data" />
      </group>
      <content name="video" senders="both">
         <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="video" />
      </content>
      <content name="audio" senders="both">
         <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio" />
      </content>
      <content name="data">
         <description xmlns="urn:xmpp:jingle:transports:webrtc-datachannel:0" />
      </content>
   </jingle>
</iq>
```

**Comment by legastero** [comment] 2015-12-09 19:50
Right the more correct approach here would be for us to define a namespace that is specifically for JVB information.

Creating a generic catch-all definition for data channels is very appealing and pragmatic, but it is an artifact of our initial approach in forcing a square Jingle peg into a round PeerConnection hole. A useful short-term hack, not a long-term solution.

The problem is that  while PeerConnection provides a data section in the SDP it generates/accepts, it does not indicate the _purpose_ for the channels, which is what the &lt;description/&gt; is for in Jingle. That is, even if two client implementations understood the generic catch-all, they still wouldn't be able to meaningfully interoperate because they won't know what to do with the channels once established.

**Comment by xdumaine** [comment] 2015-12-09 20:25
That being the case, I'd be willing to use the specific namespace you're using for talky in the short term.

**Comment by fippo** [comment] 2018-05-04 08:23
@legastero did we kill the old namespace?

**Closed as not planned** 2023-04-03 13:02 UTC
